# Generated by Django 5.2.5 on 2025-08-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('default_storage_days', models.IntegerField()),
            ],
            options={
                'verbose_name': '식품 카테고리',
                'verbose_name_plural': '식품 카테고리들',
            },
        ),
    ]
