# Generated by Django 5.2.5 on 2025-08-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='default_storage_days',
            field=models.IntegerField(verbose_name='기본 보관일'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='대분류'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='subcategory',
            field=models.CharField(max_length=50, verbose_name='소분류'),
        ),
    ]
