# Generated by Django 5.2.5 on 2025-08-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_alter_foodcategory_default_storage_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='식품명')),
                ('is_main_button', models.BooleanField(default=False, verbose_name='메인 버튼 표시')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.foodcategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '식품',
                'verbose_name_plural': '식품들',
            },
        ),
    ]
