# Generated by Django 5.2.5 on 2025-08-08 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': '식품카테고리', 'verbose_name_plural': '식품카테고리들'},
        ),
        migrations.AlterField(
            model_name='food',
            name='is_main_button',
            field=models.BooleanField(default=False, verbose_name='메인버튼 표시'),
        ),
        migrations.CreateModel(
            name='FoodMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.CharField(max_length=100, verbose_name='검색키워드')),
                ('confidence_level', models.FloatField(default=1.0, verbose_name='신뢰도')),
                ('mapped_to_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.food', verbose_name='매핑될식품')),
            ],
            options={
                'verbose_name': '식품매핑',
                'verbose_name_plural': '식품매핑들',
                'unique_together': {('search_keyword', 'mapped_to_food')},
            },
        ),
    ]
