# Generated by Django 5.2.5 on 2025-08-08 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_alter_foodcategory_options_alter_food_is_main_button_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_discount', models.BooleanField(default=False, verbose_name='할인상품')),
                ('urgency', models.CharField(blank=True, choices=[('today', '오늘'), ('tomorrow', '내일'), ('day_after_tomorrow', '모레')], max_length=20, null=True, verbose_name='언제까지')),
                ('is_consumed', models.BooleanField(default=False, verbose_name='소비 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='냉장고 등록일시')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.food', verbose_name='식품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '냉장고 아이템',
                'verbose_name_plural': '냉장고 아이템들',
                'ordering': ['-created_at'],
            },
        ),
    ]
